# Generated by Django 4.2.16 on 2025-01-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webdata", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="account_type2",
        ),
    ]
