# Generated by Django 4.2.16 on 2025-01-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webdata", "0003_delete_newtable_alter_customerinfo_lat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlog",
            name="avail_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("unavailable", "Unavailable"),
                    ("expired", "Expired"),
                ],
                default="available",
                max_length=50,
            ),
        ),
    ]
