# Generated by Django 4.2.16 on 2025-02-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webdata", "0004_alter_foodlog_avail_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservationlog",
            name="collected",
        ),
        migrations.AddField(
            model_name="reservationlog",
            name="res_status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("collected", "Collected"),
                    ("expired", "Expired"),
                ],
                default="open",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="reservationlog",
            name="collection_date_time",
            field=models.DateTimeField(default="2025-02-01 14:45:20.262568+08"),
            preserve_default=False,
        ),
    ]
