# Generated by Django 4.2.16 on 2025-02-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webdata", "0006_alter_reservationlog_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservationlog",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="reservationlog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("res_status", "open")),
                fields=("item", "customer"),
                name="unique_available_reservation",
            ),
        ),
    ]
