# Generated by Django 4.2.16 on 2025-02-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webdata", "0007_alter_reservationlog_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlog",
            name="units",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
