# Generated by Django 4.2.16 on 2025-02-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webdata", "0008_alter_foodlog_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlog",
            name="units",
            field=models.CharField(default="Unit", max_length=50),
            preserve_default=False,
        ),
    ]
