# Generated by Django 4.2.16 on 2025-02-23 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webdata", "0011_alter_foodlog_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlog",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_items",
                to="webdata.businessinfo",
            ),
        ),
        migrations.AlterField(
            model_name="reservationlog",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="webdata.foodlog",
            ),
        ),
    ]
