# Generated by Django 4.2.16 on 2025-02-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webdata", "0012_alter_foodlog_business_alter_reservationlog_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessinfo",
            name="business_image",
            field=models.ImageField(
                blank=True,
                default="business/default.jpg",
                null=True,
                upload_to="business/",
            ),
        ),
    ]
