# Generated by Django 4.2.16 on 2025-02-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webdata", "0013_businessinfo_business_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietaryReg",
            fields=[
                ("dietary_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "dietary_opt",
                    models.CharField(
                        choices=[
                            ("vegetarian", "Vegetarian"),
                            ("vegan", "Vegan"),
                            ("kosher", "Kosher"),
                            ("halal", "Halal"),
                            ("jain", "Jain"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webdata.businessinfo",
                    ),
                ),
            ],
            options={
                "unique_together": {("business", "dietary_opt")},
            },
        ),
        migrations.DeleteModel(
            name="DietaryNeeds",
        ),
    ]
