# Generated by Django 4.2.16 on 2025-03-19 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webdata", "0016_remove_fooditem_business_delete_alert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="business",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="webdata.businessinfo",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="customer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="webdata.customerinfo",
            ),
        ),
    ]
