# Generated by Django 4.2.16 on 2025-03-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webdata", "0017_alter_customuser_business_alter_customuser_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietaryreg",
            name="dietary_opt",
            field=models.CharField(
                choices=[
                    ("vegetarian", "Vegetarian"),
                    ("vegan", "Vegan"),
                    ("kosher", "Kosher"),
                    ("halal", "Halal"),
                    ("jain", "Jain"),
                    ("glutenfree", "Gluten-free"),
                ],
                default=3,
            ),
        ),
    ]
